### ISSUE TITLE
无法创建新项目

### ISSUE THREAD

**Issue by qm3cs** [bit4woo/domain_hunter_pro#17]
师傅，请教一下，该插件在java8和java11以及java16环境下，都无法新建项目，具体为右键Domain Hunter Pro无响应，是不是需要另外设置其他东西，望解答，感谢师傅！

**Comment by bit4woo** [comment]
没有理解你遇到的问题，具体在做什么操作的时候出现了无响应？

**Comment by Ajatars** [comment]
同，右键标签的时候没有下拉菜单，无法创建新项目

**Comment by bit4woo** [comment]
请提供截图或报错信息

**Comment by hhroot** [comment]
同样的问题，Domain Hunter Pro无法出现说明里面的标签栏（也没有报错之类的）

**Comment by bit4woo** [comment]
是看不到这个菜单吗？
![image](https://user-images.githubusercontent.com/8793481/125228806-0b137480-e308-11eb-97f1-7c481907c6cf.png)

**Comment by hhroot** [comment]
是的

**Comment by bit4woo** [comment]
试试最新代码，需要自己打一下包：

git clone https://github.com/bit4woo/domain_hunter_pro
cd domain_hunter_pro
mvn package

如果再遇到问题应该会有错误信息显示的，麻烦提交给我。
@hhroot @SWING-D @Ajatars

**Comment by hhroot** [comment]
重新构建了，但是利用生成的jar文件依然无法出现之前的创建数据库的菜单选项 @bit4woo 
![Snipaste_2021-07-12_16-27-20](https://user-images.githubusercontent.com/29162271/125255784-5fc9e600-e32e-11eb-9cd9-9fce3296f44e.png)  

target文件夹中的文件（我用的是domain_hunter_pro-v1.2-jar-with-dependencies.jar）
![Snipaste_2021-07-12_16-26-46](https://user-images.githubusercontent.com/29162271/125256472-0ca46300-e32f-11eb-937a-bdcc06d2290b.png)

使用target里面的domain_hunter_pro-v1.2.jar会报错，详细如下
![Snipaste_2021-07-12_16-33-22](https://user-images.githubusercontent.com/29162271/125256271-e2eb3c00-e32e-11eb-9415-84e8d32061d0.png)

**Comment by bit4woo** [comment]
请使用 domain_hunter_pro-v1.2-jar-with-dependencies.jar进行测试，是否有报错信息

**Comment by hhroot** [comment]
> 请使用 domain_hunter_pro-v1.2-jar-with-dependencies.jar进行测试，是否有报错信息

omain_hunter_pro-v1.2-jar-with-dependencies.jar无报错信息，但是还是没有新建项目的选项

**Comment by bit4woo** [comment]
@hhroot 加我微信沟通一下 搜索 bit4woo

**Comment by yanghaoi** [comment]
v1.7.33，	jdk1.8 

at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at burp.BurpExtender.QueueToResult(BurpExtender.java:122)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:232)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at burp.BurpExtender.QueueToResult(BurpExtender.java:122)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:232)
	at burp.vec.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:358)
	at GUI.LineEntryMenuForBurp$setLevelAsActionListener$1.doInBackground(LineEntryMenuForBurp.java:344)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)
java.lang.NullPointerException
	at domain.DomainProducer.run(DomainProducer.java:81)

**Comment by hhroot** [comment]
> 师傅，请教一下，该插件在java8和java11以及java16环境下，都无法新建项目，具体为右键Domain Hunter Pro无响应，是不是需要另外设置其他东西，望解答，感谢师傅！

在这
![Snipaste_2021-07-15_11-15-37](https://user-images.githubusercontent.com/29162271/125723607-edf6a569-8bf9-4eed-bc94-39957de15cf6.png)

**Comment by 0ks3iio** [comment]
java.lang.NullPointerException
	at domain.DomainProducer.classifyDomain(DomainProducer.java:135)
	at domain.DomainProducer.run(DomainProducer.java:88)

**Comment by bit4woo** [comment]
@0ks3iio 已修复

**Comment by peanut-cc** [comment]
问题好像还是有
```
java.lang.NullPointerException: Cannot invoke "javax.swing.JMenuBar.getMenuCount()" because "menuBar" is null
        at GUI.ProjectMenu.Add(ProjectMenu.java:28)
        at GUI.GUI.<init>(GUI.java:78)
        at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:154)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at burp.h8l.lambda$registerExtenderCallbacks$0(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Database FileName From Extension Setting: null
Table created successfully
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  | 2021-08-16 22:05:35 | [AWT-EventQueue-0] burp.DBHelper (DBHelper.java:74) - Table created successfully
Table created successfully
INFO  | 2021-08-16 22:05:35 | [AWT-EventQueue-0] burp.DBHelper (DBHelper.java:84) - Table created successfully
java.lang.NullPointerException: Cannot invoke "domain.DomainManager.getProjectName()" because "domainResult" is null
        at burp.DBHelper.saveDomainObject(DBHelper.java:162)
        at domain.DomainPanel.saveDomainOnly(DomainPanel.java:1151)
        at domain.DomainPanel$1.actionPerformed(DomainPanel.java:110)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsoluteFile()" because "file" is null
        at domain.DomainPanel.backupDB(DomainPanel.java:1242)
        at domain.DomainPanel$7.actionPerformed(DomainPanel.java:359)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsoluteFile()" because "file" is null
        at domain.DomainPanel.backupDB(DomainPanel.java:1242)
        at domain.DomainPanel$7.actionPerformed(DomainPanel.java:359)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsoluteFile()" because "file" is null
        at domain.DomainPanel.backupDB(DomainPanel.java:1242)
        at domain.DomainPanel$7.actionPerformed(DomainPanel.java:359)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by bit4woo** [comment]
有时候在打开burp的过程中，图形界面加载慢了可以会出现这个问题，现已修复。 @peanut-cc 

试试最新代码，需要自己打一下包：

git clone https://github.com/bit4woo/domain_hunter_pro
cd domain_hunter_pro
mvn package
